### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dondakeshimo** [dondakeshimo/predicting-molecular-properties#2]
- [x] add chemical bond feature
 - [x] separate model for each molecule types
 - [x] set first training target to fc
 - [x] use NN
 - [ ] use stacked generalization
 - [ ] visualize training history
 - [ ] optimize each types
 - [ ] check group mae in nn. lgb's group mae goes under 0, but nn's is never.
 - [ ] use model check point to get best weight
